# Store of mappings of each record in XP-810 .dat files

record_maps = [
    {
        "name": "ndb_navaid",
        "row_code": "2",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "NDB_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "NDB_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "NDB_Elevation"},
            {"id": 5, "start": 38, "end": 41, "name": "NDB_Frequency"},
            {"id": 6, "start": 42, "end": 45, "name": "NDB_RangeNM"},
            {"id": 7, "start": 53, "end": 56, "name": "NDB_Identifier"},
            {"id": 8, "start": 58, "end": 99, "name": "NDB_Name"},
        ],
    },
    {
        "name": "vhf_navaid",
        "row_code": "3",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "VOR_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "VOR_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "VOR_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "VOR_Frequency"},
            {"id": 6, "start": 42, "end": 45, "name": "VOR_RangeNM"},
            {"id": 7, "start": 46, "end": 52, "name": "VOR_SlaveVar"},
            {"id": 8, "start": 53, "end": 57, "name": "VOR_Identifier"},
            {"id": 9, "start": 58, "end": 99, "name": "VOR_Name"},
        ],
    },
    {
        "name": "localizer",
        "row_code": "4",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "Localizer_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "Localizer_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "Localizer_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "Localizer_Frequency"},
            {"id": 6, "start": 42, "end": 45, "name": "Localizer_RangeNM"},
            {"id": 7, "start": 50, "end": 57, "name": "Localizer_Bearing"},
            {"id": 8, "start": 58, "end": 62, "name": "Localizer_Identifier"},
            {"id": 9, "start": 63, "end": 67, "name": "Airport_Identifier"},
            {"id":10, "start": 68, "end": 71, "name": "Runway_Identifier"},
            {"id":11, "start": 72, "end": 99, "name": "Localizer_Name"},
        ],
    },
    {
        "name": "localizer_noGS",
        "row_code": "5",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "Localizer_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "Localizer_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "Localizer_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "Localizer_Frequency"},
            {"id": 6, "start": 42, "end": 45, "name": "Localizer_RangeNM"},
            {"id": 7, "start": 50, "end": 57, "name": "Localizer_BrngTrue"},
            {"id": 8, "start": 58, "end": 62, "name": "Localizer_Identifier"},
            {"id": 9, "start": 63, "end": 67, "name": "Airport_Identifier"},
            {"id":10, "start": 68, "end": 71, "name": "Runway_Identifier"},
            {"id":11, "start": 72, "end": 99, "name": "Localizer_Name"},
        ],
    },
    {
        "name": "glideslope",
        "row_code": "6",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "Glide_Slope_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "Glide_Slope_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "Glide_Slope_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "Glide_Slope_Frequency"},
            {"id": 6, "start": 42, "end": 45, "name": "Glide_Slope_RangeNM"},
            {"id": 7, "start": 47, "end": 50, "name": "Glide_Slope_Angle"},
            {"id": 8, "start": 50, "end": 57, "name": "Glide_Slope_BrngTrue"},
            {"id": 9, "start": 58, "end": 62, "name": "Glide_Slope_Identifier"},
            {"id":10, "start": 63, "end": 67, "name": "Airport_Identifier"},
            {"id":11, "start": 68, "end": 71, "name": "Runway_Identifier"},
            {"id":12, "start": 72, "end": 99, "name": "Glide_Slope_Name"},
        ],
    },
    {
        "name": "ndat_om",
        "row_code": "7",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "OM_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "OM_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "OM_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "OM_Frequency"},
            {"id": 7, "start": 50, "end": 57, "name": "OM_BrngTrue"},
            {"id": 8, "start": 58, "end": 62, "name": "OM_IdentNU"},
            {"id": 9, "start": 63, "end": 67, "name": "OM_ICAO"},
            {"id":10, "start": 68, "end": 71, "name": "OM_Rway"},
            {"id":11, "start": 72, "end": 99, "name": "OM_Name"},
        ],
    },
    {
        "name": "ndat_mm",
        "row_code": "8",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "MM_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "MM_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "MM_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "MM_Frequency"},
            {"id": 7, "start": 50, "end": 57, "name": "MM_BrngTrue"},
            {"id": 8, "start": 58, "end": 62, "name": "MM_IdentNU"},
            {"id": 9, "start": 63, "end": 67, "name": "MM_ICAO"},
            {"id":10, "start": 68, "end": 71, "name": "MM_Rway"},
            {"id":11, "start": 72, "end": 99, "name": "MM_Name"},
        ],
    },
    {
        "name": "ndat_im",
        "row_code": "9",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  1, "name": "Row_Code"},
            {"id": 2, "start":  2, "end": 14, "name": "IM_Latitude"},
            {"id": 3, "start": 15, "end": 28, "name": "IM_Longitude"},
            {"id": 4, "start": 30, "end": 35, "name": "IM_Elevation"},
            {"id": 5, "start": 36, "end": 41, "name": "IM_Frequency"},
            {"id": 7, "start": 50, "end": 57, "name": "IM_BrngTrue"},
            {"id": 8, "start": 58, "end": 62, "name": "IM_Identifier"},
            {"id": 9, "start": 63, "end": 67, "name": "IM_ICAO"},
            {"id":10, "start": 68, "end": 71, "name": "IM_Rway"},
            {"id":11, "start": 72, "end": 99, "name": "IM_Name"},
        ],
    },
    {
        "name": "ndat_dme",
        "row_code": "12",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  2, "name": "Row_Code"},
            {"id": 2, "start":  3, "end": 15, "name": "DME_Latitude"},
            {"id": 3, "start": 16, "end": 29, "name": "DME_Longitude"},
            {"id": 4, "start": 30, "end": 36, "name": "DME_Elevation"},
            {"id": 5, "start": 37, "end": 42, "name": "DME_Frequency"},
            {"id": 7, "start": 43, "end": 46, "name": "DME_RngeNM"},
            {"id": 8, "start": 50, "end": 58, "name": "DME_BiasNM"},
            {"id": 9, "start": 59, "end": 62, "name": "DME_Identifier"},
            {"id": 9, "start": 63, "end": 68, "name": "DME_ICAO"},
            {"id":10, "start": 69, "end": 72, "name": "DME_Rway"},
            {"id":11, "start": 73, "end": 99, "name": "DME_Name"},
        ],
    },
    {
        "name": "ndat_dme_dfrq",
        "row_code": "13",
        "rowcode_posn": 0,
        "columns": [
            {"id": 1, "start":  0, "end":  2, "name": "Row_Code"},
            {"id": 2, "start":  3, "end": 15, "name": "DME_Latitude"},
            {"id": 3, "start": 16, "end": 29, "name": "DME_Longitude"},
            {"id": 4, "start": 30, "end": 36, "name": "DME_Elevation"},
            {"id": 5, "start": 37, "end": 42, "name": "DME_Frequency"},
            {"id": 7, "start": 43, "end": 46, "name": "DME_RngeNM"},
            {"id": 8, "start": 50, "end": 58, "name": "DME_BiasNM"},
            {"id": 9, "start": 59, "end": 62, "name": "DME_Identifier"},
            {"id": 9, "start": 63, "end": 68, "name": "DME_ICAO"},
            {"id":10, "start": 69, "end": 72, "name": "DME_Rway"},
            {"id":11, "start": 73, "end": 99, "name": "DME_Name"},
        ],
    },
]
